"""Pytest wiring for the design-truth tools.

The tools import each other by bare name (`import entity_map_build`), so this
directory goes on sys.path.

Hermeticity is structural, not disciplinary. entity_map_build's paths are
module-level constants pointing at the REAL map and the REAL views, so a test
that calls main() by accident silently rewrites production. The autouse
fixture below snapshots the whole truth DIRECTORY around every test — files,
not a remembered list of files — and fails loudly naming what moved.
"""
from __future__ import annotations

import hashlib
import sys
from collections.abc import Iterator
from pathlib import Path

import pytest

HERE = Path(__file__).parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))


def _snapshot() -> dict[str, str]:
    """Content hash per file under the truth directory. Caches are excluded:
    they are generated by the act of running the tests themselves."""
    out: dict[str, str] = {}
    for path in sorted(HERE.rglob("*")):
        if path.is_dir() or "__pycache__" in path.parts:
            continue
        out[str(path.relative_to(HERE))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return out


@pytest.fixture(autouse=True)
def production_untouched() -> Iterator[None]:
    before = _snapshot()
    yield
    after = _snapshot()
    added = sorted(set(after) - set(before))
    removed = sorted(set(before) - set(after))
    changed = sorted(k for k in set(before) & set(after) if before[k] != after[k])
    assert not (added or removed or changed), (
        "a test wrote into production truth artifacts: "
        f"changed={changed} added={added} removed={removed}"
    )
